[project]
name = "seed-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bip-utils==2.0.0",
    "blocksmith>=1.2.1",
    "requests>=2.32.3",
]
